# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab4/lab4.srcs/sources_1/ip/lcd_controller_0/lcd_controller_0.xci
# IP: The module: 'lcd_controller_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab4/lab4.srcs/sources_1/ip/lcd_controller_0/ip/text_bram/text_bram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==text_bram || ORIG_REF_NAME==text_bram} -quiet] -quiet

# IP: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab4/lab4.srcs/sources_1/ip/lcd_controller_0/ip/rst_rom/rst_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rst_rom || ORIG_REF_NAME==rst_rom} -quiet] -quiet

# IP: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab4/lab4.srcs/sources_1/ip/lcd_controller_0/ip/font_rom/font_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==font_rom || ORIG_REF_NAME==font_rom} -quiet] -quiet

# XDC: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab4/lab4.srcs/sources_1/ip/lcd_controller_0/ip/text_bram/text_bram_ooc.xdc

# XDC: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab4/lab4.srcs/sources_1/ip/lcd_controller_0/ip/rst_rom/rst_rom_ooc.xdc

# XDC: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab4/lab4.srcs/sources_1/ip/lcd_controller_0/ip/font_rom/font_rom_ooc.xdc

# IP: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab4/lab4.srcs/sources_1/ip/lcd_controller_0/lcd_controller_0.xci
# IP: The module: 'lcd_controller_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab4/lab4.srcs/sources_1/ip/lcd_controller_0/ip/text_bram/text_bram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==text_bram || ORIG_REF_NAME==text_bram} -quiet] -quiet

# IP: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab4/lab4.srcs/sources_1/ip/lcd_controller_0/ip/rst_rom/rst_rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rst_rom || ORIG_REF_NAME==rst_rom} -quiet] -quiet

# IP: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab4/lab4.srcs/sources_1/ip/lcd_controller_0/ip/font_rom/font_rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==font_rom || ORIG_REF_NAME==font_rom} -quiet] -quiet

# XDC: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab4/lab4.srcs/sources_1/ip/lcd_controller_0/ip/text_bram/text_bram_ooc.xdc

# XDC: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab4/lab4.srcs/sources_1/ip/lcd_controller_0/ip/rst_rom/rst_rom_ooc.xdc

# XDC: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab4/lab4.srcs/sources_1/ip/lcd_controller_0/ip/font_rom/font_rom_ooc.xdc
