set_property PACKAGE_PIN AC19 [get_ports sys_clk]
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets sys_clk]
create_clock -period 10.000 -name sys_clk -waveform {0.000 5.000} [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]


set_property PACKAGE_PIN Y3 [get_ports sys_rstn]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rstn]

set_property PACKAGE_PIN H9 [get_ports {lcd_db[0]}]
set_property PACKAGE_PIN K17 [get_ports {lcd_db[1]}]
set_property PACKAGE_PIN J20 [get_ports {lcd_db[2]}]
set_property PACKAGE_PIN M17 [get_ports {lcd_db[3]}]
set_property PACKAGE_PIN L17 [get_ports {lcd_db[4]}]
set_property PACKAGE_PIN L18 [get_ports {lcd_db[5]}]
set_property PACKAGE_PIN L15 [get_ports {lcd_db[6]}]
set_property PACKAGE_PIN M15 [get_ports {lcd_db[7]}]
set_property PACKAGE_PIN M16 [get_ports {lcd_db[8]}]
set_property PACKAGE_PIN L14 [get_ports {lcd_db[9]}]
set_property PACKAGE_PIN M14 [get_ports {lcd_db[10]}]
set_property PACKAGE_PIN F22 [get_ports {lcd_db[11]}]
set_property PACKAGE_PIN G22 [get_ports {lcd_db[12]}]
set_property PACKAGE_PIN G21 [get_ports {lcd_db[13]}]
set_property PACKAGE_PIN H24 [get_ports {lcd_db[14]}]
set_property PACKAGE_PIN J16 [get_ports {lcd_db[15]}]

set_property PACKAGE_PIN J25 [get_ports lcd_rst]
set_property PACKAGE_PIN H18 [get_ports lcd_cs]
set_property PACKAGE_PIN K16 [get_ports lcd_rs]
set_property PACKAGE_PIN L8 [get_ports lcd_wr]
set_property PACKAGE_PIN K8 [get_ports lcd_rd]
set_property PACKAGE_PIN J15 [get_ports lcd_bl_ctr]

set_property IOSTANDARD LVCMOS33 [get_ports lcd_rst]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_cs]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_rs]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_rd]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_wr]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_db[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_bl_ctr]