# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab4/lab4.srcs/sources_1/ip/ma_river_core_0/ma_river_core_0.xci
# IP: The module: 'ma_river_core_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab4/lab4.srcs/sources_1/ip/ma_river_core_0/ip/bram_td/bram_td.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_td || ORIG_REF_NAME==bram_td} -quiet] -quiet

# IP: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab4/lab4.srcs/sources_1/ip/ma_river_core_0/ip/bram_sd/bram_sd.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_sd || ORIG_REF_NAME==bram_sd} -quiet] -quiet

# XDC: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab4/lab4.srcs/sources_1/ip/ma_river_core_0/ip/bram_td/bram_td_ooc.xdc

# XDC: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab4/lab4.srcs/sources_1/ip/ma_river_core_0/ip/bram_sd/bram_sd_ooc.xdc

# IP: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab4/lab4.srcs/sources_1/ip/ma_river_core_0/ma_river_core_0.xci
# IP: The module: 'ma_river_core_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab4/lab4.srcs/sources_1/ip/ma_river_core_0/ip/bram_td/bram_td.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_td || ORIG_REF_NAME==bram_td} -quiet] -quiet

# IP: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab4/lab4.srcs/sources_1/ip/ma_river_core_0/ip/bram_sd/bram_sd.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_sd || ORIG_REF_NAME==bram_sd} -quiet] -quiet

# XDC: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab4/lab4.srcs/sources_1/ip/ma_river_core_0/ip/bram_td/bram_td_ooc.xdc

# XDC: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab4/lab4.srcs/sources_1/ip/ma_river_core_0/ip/bram_sd/bram_sd_ooc.xdc
