# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab5/lab5.srcs/sources_1/ip/cpu_data_ram/cpu_data_ram.xci
# IP: The module: 'cpu_data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab5/lab5.srcs/sources_1/ip/cpu_data_ram/cpu_data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_data_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab5/lab5.srcs/sources_1/ip/cpu_data_ram/cpu_data_ram.xci
# IP: The module: 'cpu_data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/lab5/lab5.srcs/sources_1/ip/cpu_data_ram/cpu_data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_data_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
